import { Provider } from "react-redux";
import Header from "./Header/page";
import "./globals.css";
import type { Metadata } from "next";
import Store from "./redux/store";
import { ReduxProvider } from "./redux/provider";

export const metadata: Metadata = {
  title: "Library Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="main-container">
        (
        <ReduxProvider>
          <Header />
          {children}
        </ReduxProvider>
        )
      </body>
    </html>
  );
}
